# Fly.io deployment configuration
app = "masumi-kodosuni-connector"
primary_region = "fra"

[build]

[env]
  PORT = "8000"
  PYTHONPATH = "/app/src"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "15s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

[experimental]
  auto_rollback = true

[[mounts]]
  destination = "/app/data"
  source = "data_volume"