"""increase payment id length

Revision ID: 001
Revises: 
Create Date: 2025-06-24 20:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_runs', 'masumi_payment_id',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.Text(),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow_runs', 'masumi_payment_id',
                    existing_type=sa.Text(),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    # ### end Alembic commands ###